esphome:
    name: esp8266_pooltemp
    platform: ESP8266
    board: esp8285
    includes:
    - pool_temp_sensor.h
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  #level: DEBUG

substitutions:
  hostname: "esp8266_pooltemp"

# Enable Home Assistant API
api:
   password: !secret api_password

ota:
   password: !secret ota_password

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new PoolTempSensor(14);
    App.register_component(my_sensor);
    return {my_sensor->temperature_sensor_channel1,my_sensor->temperature_sensor_channel2,my_sensor->temperature_sensor_channel3};

  sensors:
  - name: "Wireless pool temperature sensor channel 1"
    unit_of_measurement: °C
    accuracy_decimals: 1
    icon: "mdi:water-percent"
    filters:
      - median:
          window_size: 5
          send_every: 5
          send_first_at: 5
  - name:  "Wireless pool temperature sensor channel 2"
    unit_of_measurement: °C
    accuracy_decimals: 1
    icon: "mdi:water-percent"
    filters:
      - median:
          window_size: 5
          send_every: 5
          send_first_at: 5
  - name:  "Wireless pool temperature sensor channel 3"
    unit_of_measurement: °C
    accuracy_decimals: 1
    icon: "mdi:water-percent"
    filters:
      - median:
          window_size: 5
          send_every: 5
          send_first_at: 5
